package com.secKillingProject.dao;

import com.secKillingProject.dataObject.ItemStockDO;
import org.apache.ibatis.annotations.Param;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Mar 30 00:26:40 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Mar 30 00:26:40 CST 2021
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Mar 30 00:26:40 CST 2021
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Mar 30 00:26:40 CST 2021
     */
    ItemStockDO selectByPrimaryKey(Integer id);

    /**通过这个接口获取到DO对象
     * selectByItemId 通过ItemId查询记录
     * */
    ItemStockDO selectByItemId(Integer itemId);

    /**传入itemId和amount，执行stock的更新*/
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Mar 30 00:26:40 CST 2021
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Mar 30 00:26:40 CST 2021
     */
    int updateByPrimaryKey(ItemStockDO record);
}