---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fucker.
--- DateTime: 2021/4/17 22:14
---ngx.log();用来操作log日志
---操纵日志打印 init lua success 这句话
---
ngx.log(ngx.ERR,"init lua success");