---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fucker.
--- DateTime: 2021/4/17 22:35
---content挂载点，挂载的lua，
---nginx判断到item/get这个url时就挂载这个lua
---这样的方式即以http response的方式打印 括号内的字符串
ngx.say("hello static item lua");